name: Start VM

on:
  repository_dispatch:
    types: [start]
  workflow_dispatch:

jobs:
  start-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI Script
        uses: azure/CLI@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az vm start --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name ${{ vars.AZURE_VM }}
